version: '3.8'

services:
  db:
    image: postgres:15
    privileged: true
    restart: always
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 777jon777
      POSTGRES_DB: noty

  backend:
    build: ./
    privileged: true
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'notification.settings'
    command: bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  celery:
    build: ./
    privileged: true
    command: celery -A notification worker -l info -P gevent
    environment:
      DJANGO_SETTINGS_MODULE: 'notification.settings'
    depends_on:
      - backend
      - rebbitmq

  rebbitmq:
    image: rebbitmq
    privileged: true
    command: docker run -d -p 5672:5672 rabbitmq
    restart: always
    ports:
      - 5672:5672

  dashboard:
    container_name: dashboard
    build: .
    command: celery flower --port=5566
    ports:
      - 5566:5566
    environment:
      - CELERY_BROKER_URL=amqp://localhost
    depends_on:
      - rebbitmq
      - web
      - celery
